version: '3.7'

services:

  parser:
    image: fppressa/nginx-fpm:1.17.9-7.4-dev
    ports:
      - 8787:80
    environment:
      DEBUG: "true"
      XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
      XDEBUG_PORT: ${XDEBUG_PORT:-9000}
    volumes:
      - .:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    networks:
      - parser_network

networks:
  parser_network:
