<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class DemoData2 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement('DELETE FROM posts ;');
        DB::statement('DELETE FROM sources ;');
        DB::statement('DELETE FROM persons ;');


        DB::statement("INSERT INTO `persons` (`id`, `name`) VALUES
                            (1,	'Анастасия Стежко'),
                            (2,	'Орландо Блум'),
                            (3,	'Егор Кончаловский'),
                            (4,	'Ирина Безрукова'),
                            (5,	'Анастасия Стриженова (дочь Екатерины Стриженовой)'),
                            (6,	'Алена Свиридова'),
                            (7,	'Анастасия Сафонова (дочь Кирилла Сафонова)'),
                            (8,	'Жизель Бюндхен'),
                            (9,	'Кирилл Нагиев (сын Дмитрия Нагиева)'),
                            (10,	'Флоранс Илли (вдова Дмитрия Хворостовского)'),
                            (11,	'Антон Криворотов'),
                            (12,	'Барбара Пино'),
                            (13,	'Евгения Медведева, фигуристка'),
                            (14,	'Аделина Сотникова'),
                            (15,	'Татьяна Брухунова'),
                            (16,	'Ксения Шевченко-Сябитова (дочь Розы Сябитовой)'),
                            (17,	'Александр Буйнов'),
                            (18,	'Елена Проклова'),
                            (19,	'Давид Манукян (бойфренд Бузовой)'),
                            (20,	'Диана Дэвис (дочь Этери Тутберидзе)'),
                            (21,	'Кирилл Туриченко (солист Иванушек)'),
                            (22,	'Елена Шевченко (мать Марии Машковой, первая жена Владимира Машкова)'),
                            (23,	'Ирина Смелая (жена солиста Little Big, Ильи Прусикина)'),
                            (24,	'Марина Газманова'),
                            (25,	'Анастасия Макаревич (солистка группы Лицей)'),
                            (26,	'Алла Довлатова'),
                            (27,	'Джанлука Вакки (танцующий миллионер)'),
                            (28,	'Василий Рыбин (сын солиста группы Дюна)'),
                            (29,	'Рэпер Niletto'),
                            (30,	'Влад Соколовский'),
                            (31,	'Эмма Хэмминг (жена Брюса Уиллиса)'),
                            (32,	'Александр Овечкин'),
                            (33,	'Мэй Маск (мама Илона)'),
                            (34,	'Татьяна Михалкова'),
                            (35,	'Светлана Пермякова'),
                            (36,	'Надежда Мейхер (экс-солистка Виа Гры)'),
                            (37,	'Ирина Нельсон'),
                            (38,	'Дмитрий Исхаков'),
                            (39,	'Юлия Волкова (татушка)'),
                            (40,	'Игорь Акинфеев'),
                            (41,	'Алена Гаврилова'),
                            (42,	'Константин Меладзе'),
                            (43,	'Лена Катина'),
                            (44,	'Джаред Лето'),
                            (45,	'Павел Погребняк'),
                            (46,	'Маргарита Грачева'),
                            (47,	'Наталья Андрейченко'),
                            (48,	'Евгений Плющенко'),
                            (49,	'Елена Задорнова (дочь Михаила Задорнова)'),
                            (50,	'Евгений Цыганов'),
                            (51,	'Эммануил Виторган'),
                            (52,	'Дарья Повереннова'),
                            (53,	'Арина Шарапова'),
                            (54,	'Стас Михайлов'),
                            (55,	'Алена Хмельницкая'),
                            (56,	'Людмила Артемьева'),
                            (57,	'Нилетто'),
                            (58,	'Антонина Паперная'),
                            (59,	'Владимир Маркони'),
                            (60,	'Гоар Аветисян'),
                            (61,	'Аня Пересильд'),
                            (62,	'Мария Порошина'),
                            (63,	'Алена Михайлова'),
                            (64,	'Варвара Шмыкова'),
                            (65,	'Никита Ефремов'),
                            (66,	'Доктор Комаровский'),
                            (67,	'Екатерина Андреева'),
                            (68,	'Алексей Ягудин'),
                            (69,	'Алина Загитова'),
                            (70,	'Софья Зайка'),
                            (71,	'Татьяна Арнтгольц'),
                            (72,	'Александр Ратников'),
                            (73,	'Анатолий Руденко'),
                            (74,	'Иван Жидков'),
                            (75,	'Юлия Ефимова'),
                            (76,	'Светлана Сурганова'),
                            (77,	'Федор Добронравов'),
                            (78,	'Анна Чурина'),
                            (79,	'Риналь Мухаметов'),
                            (80,	'Ксения Теплова'),
                            (81,	'Юлия Хлынина'),
                            (82,	'Евгения Брик'),
                            (83,	'Павел Прилучный'),
                            (84,	'Глафира Тарханова'),
                            (85,	'Ольга Медынич'),
                            (86,	'Милош Бикович'),
                            (87,	'Юлия Топольницкая'),
                            (88,	'Юлия Ковальчук'),
                            (89,	'Любовь Аксенова'),
                            (90,	'Дмитрий Исхаков'),
                            (91,	'Глюкоза'),
                            (92,	'Анна Михайловская'),
                            (93,	'Сабина Ахмедова'),
                            (94,	'Кирилл Жданов'),
                            (95,	'Катя Варнава'),
                            (96,	'София Каштанова'),
                            (97,	'Александра Ребенок'),
                            (98,	'Анжелика Каширина'),
                            (99,	'Дарья Мороз'),
                            (100,	'Павел Трубинер'),
                            (101,	'Влад Лисовец'),
                            (102,	'Сергей Полунин'),
                            (103,	'Елена Ильиных'),
                            (104,	'Агата Муцениеце'),
                            (105,	'Максим Фадеев'),
                            (106,	'Тата Бондарчук'),
                            (107,	'Наталья Горожанова'),
                            (108,	'Яна Кошкина'),
                            (109,	'Матильда Шнурова'),
                            (110,	'Алсу'),
                            (111,	'Полина Гагарина'),
                            (112,	'Кайя Гербер'),
                            (113,	'Тимати'),
                            (114,	'Светлана Бондарчук'),
                            (115,	'Светлана Лобода'),
                            (116,	'Виктория Лопырева'),
                            (117,	'Айза Анохина'),
                            (118,	'Кэти Топурия'),
                            (119,	'Саша Морозова'),
                            (120,	'Ирина Антоненко'),
                            (121,	'Анна Хилькевич'),
                            (122,	'Джиган'),
                            (123,	'Алика Смехова'),
                            (124,	'Виктория Бекхэм'),
                            (125,	'Лера Кудрявцева'),
                            (126,	'Ольга Картункова'),
                            (127,	'Белла Хадид'),
                            (128,	'Джиджи Хадид'),
                            (129,	'Ирина Шейк'),
                            (130,	'Ангелина Долина'),
                            (131,	'Надежда Михалкова'),
                            (132,	'Дарья Клюкина'),
                            (133,	'Юлия Барановская'),
                            (134,	'Юлия Проскурякова'),
                            (135,	'Алена Шишкова'),
                            (136,	'Дима Билан'),
                            (137,	'Алекса'),
                            (138,	'Юлия Меньшова'),
                            (139,	'Гоша Куценко'),
                            (140,	'Лена Перминова'),
                            (141,	'Андрей Кончаловский'),
                            (142,	'Кристина Асмус'),
                            (143,	'Лиза Арзамасова'),
                            (144,	'Роузи Хантингтон-Уайтли'),
                            (145,	'Николай Цискаридзе'),
                            (146,	'Марк Джейкобс'),
                            (147,	'Ким Кардашьян'),
                            (148,	'Мария Ивакова'),
                            (149,	'Анна Тихомирова'),
                            (150,	'Мирослава Карпович');");

        DB::statement("INSERT INTO `sources` ( `personId`, `active`, `type`, `code`) VALUES
                        (	1,	1,	'instagram',	'nastya_stezhko'),
                        (	2,	1,	'instagram',	'orlandobloom'),
                        (	3,	1,	'instagram',	'egorkonchalovsky'),
                        (	4,	1,	'instagram',	'irina_bezrukova_official'),
                        (	5,	1,	'instagram',	'anastasia_strizhenova'),
                        (	6,	1,	'instagram',	'alenasviridova'),
                        (	7,	1,	'instagram',	'anastasiasaf'),
                        (	8,	1,	'instagram',	'gisele'),
                        (	9,	1,	'instagram',	'kirill_nagiev'),
                        (	10,	1,	'instagram',	'flosha1'),
                        (	11,	1,	'instagram',	'dr.krivorotov'),
                        (	12,	1,	'instagram',	'solansbarbara'),
                        (	13,	1,	'instagram',	'jmedvedevaj'),
                        (	14,	1,	'instagram',	'adelina_sotnikova14'),
                        (	15,	1,	'instagram',	'bruhunova'),
                        (	16,	1,	'instagram',	'k_syaba'),
                        (	17,	1,	'instagram',	'buinovofficial'),
                        (	18,	1,	'instagram',	'alenaproklova'),
                        (	19,	1,	'instagram',	'dava_m'),
                        (	20,	1,	'instagram',	'di__davis'),
                        (	21,	1,	'instagram',	'kirillturichenko'),
                        (	22,	1,	'instagram',	'shevchenko9114'),
                        (	23,	1,	'instagram',	'smelaya_ira'),
                        (	24,	1,	'instagram',	'marinagazmanova'),
                        (	25,	1,	'instagram',	'anastasiya_makarevich_official'),
                        (	26,	1,	'instagram',	'alla_dovlatova'),
                        (	27,	1,	'instagram',	'gianlucavacchi'),
                        (	28,	1,	'instagram',	'basil_r_official'),
                        (	29,	1,	'instagram',	'niletto_official'),
                        (	30,	1,	'instagram',	'vs20'),
                        (	31,	1,	'instagram',	'emmahemingwillis'),
                        (	32,	1,	'instagram',	'aleksandrovechkinofficial'),
                        (	33,	1,	'instagram',	'mayemusk'),
                        (	34,	1,	'instagram',	'tatyanamixalkova'),
                        (	35,	1,	'instagram',	's_permyakova'),
                        (	36,	1,	'instagram',	'nadyameiher'),
                        (	37,	1,	'instagram',	'irinanelson'),
                        (	38,	1,	'instagram',	'isxakov'),
                        (	39,	1,	'instagram',	'official_juliavolkova'),
                        (	40,	1,	'instagram',	'akinfeevigor_offlcial'),
                        (	41,	1,	'instagram',	'agavrilova777'),
                        (	42,	1,	'instagram',	'meladzemusic'),
                        (	43,	1,	'instagram',	'lenakatina'),
                        (	44,	1,	'instagram',	'jaredleto'),
                        (	45,	1,	'instagram',	'poga8'),
                        (	46,	1,	'instagram',	'margoritka1211'),
                        (	47,	1,	'instagram',	'natalya_andreychenko'),
                        (	48,	1,	'instagram',	'plushenkoofficial'),
                        (	49,	1,	'instagram',	'jzadornova'),
                        (	50,	1,	'instagram',	'tsyganovpictures'),
                        (	51,	1,	'instagram',	'emmanuil_vitorgan'),
                        (	52,	1,	'instagram',	'dpoverennova'),
                        (	53,	1,	'instagram',	'arinasharapova1tv_official'),
                        (	54,	1,	'instagram',	'stas_mihailoff'),
                        (	55,	1,	'instagram',	'alxmel'),
                        (	56,	1,	'instagram',	'liudmilartemyeva'),
                        (	57,	1,	'instagram',	'niletto_official'),
                        (	58,	1,	'instagram',	'tonya_papernaya'),
                        (	59,	1,	'instagram',	'vovapcdonail'),
                        (	60,	1,	'instagram',	'goar_avetisyan'),
                        (	61,	1,	'instagram',	'ankaperesild'),
                        (	62,	1,	'instagram',	'poroshinamariyamikhaylovna'),
                        (	63,	1,	'instagram',	'mikhailova_al'),
                        (	64,	1,	'instagram',	'barbaraska_92'),
                        (	65,	1,	'instagram',	'efremovefremov'),
                        (	66,	1,	'instagram',	'uakomar'),
                        (	67,	1,	'instagram',	'ekaterinaandreeva_official'),
                        (	68,	1,	'instagram',	'alexei.yagudin'),
                        (	69,	1,	'instagram',	'azagitova'),
                        (	70,	1,	'instagram',	'zaykasofya'),
                        (	71,	1,	'instagram',	'tarntgoltsofficial'),
                        (	72,	1,	'instagram',	'alex_ratnikov'),
                        (	73,	1,	'instagram',	'to100nado'),
                        (	74,	1,	'instagram',	'ivantsarevitch1'),
                        (	75,	1,	'instagram',	'pryanya93'),
                        (	76,	1,	'instagram',	'surganova_official'),
                        (	77,	1,	'instagram',	'dobronravov.fedor'),
                        (	78,	1,	'instagram',	'annachurina'),
                        (	79,	1,	'instagram',	'rinal_mukhametov'),
                        (	80,	1,	'instagram',	'kseniateplova'),
                        (	81,	1,	'instagram',	'yulia_hlynina'),
                        (	82,	1,	'instagram',	'evgeniabrik'),
                        (	83,	1,	'instagram',	'bugevuge'),
                        (	84,	1,	'instagram',	'glafiratarhanova'),
                        (	85,	1,	'instagram',	'medynich'),
                        (	86,	1,	'instagram',	'bikovic'),
                        (	87,	1,	'instagram',	'juliatopolnitskaya'),
                        (	88,	1,	'instagram',	'juliakovalchuk'),
                        (	89,	1,	'instagram',	'im_lyubovaksenova'),
                        (	90,	1,	'instagram',	'isxakov'),
                        (	91,	1,	'instagram',	'glukozamusic'),
                        (	92,	1,	'instagram',	'anna_mihailovskaya'),
                        (	93,	1,	'instagram',	'sabinaakhmedova'),
                        (	94,	1,	'instagram',	'kirill_zhandarov'),
                        (	95,	1,	'instagram',	'kativarnava'),
                        (	96,	1,	'instagram',	'sofiacastanova'),
                        (	97,	1,	'instagram',	'sasharebenok'),
                        (	98,	1,	'instagram',	'likakashirina'),
                        (	99,	1,	'instagram',	'd_moroz'),
                        (	100,	1,	'instagram',	'paveltrubiner_official'),
                        (	101,	1,	'instagram',	'vladislavlisovets'),
                        (	102,	1,	'instagram',	'poluninink'),
                        (	103,	1,	'instagram',	'blackswanei'),
                        (	104,	1,	'instagram',	'agataagata'),
                        (	105,	1,	'instagram',	'fadeevmaxim'),
                        (	106,	1,	'instagram',	'tatamamik'),
                        (	107,	1,	'instagram',	'gorozhanova'),
                        (	108,	1,	'instagram',	'yana_koshkina_official'),
                        (	109,	1,	'instagram',	'matilda.shnurova'),
                        (	110,	1,	'instagram',	'alsou_a'),
                        (	111,	1,	'instagram',	'gagara1987'),
                        (	112,	1,	'instagram',	'kaiagerber'),
                        (	113,	1,	'instagram',	'timatiofficial'),
                        (	114,	1,	'instagram',	'a030aa'),
                        (	115,	1,	'instagram',	'lobodaofficial'),
                        (	116,	1,	'instagram',	'lopyrevavika'),
                        (	117,	1,	'instagram',	'aizalovesam'),
                        (	118,	1,	'instagram',	'keti_one_official'),
                        (	119,	1,	'instagram',	'mami_doch'),
                        (	120,	1,	'instagram',	'irina8antonenko'),
                        (	121,	1,	'instagram',	'annakhilkevich'),
                        (	122,	1,	'instagram',	'iamgeegun'),
                        (	123,	1,	'instagram',	'alika_smekhova'),
                        (	124,	1,	'instagram',	'victoriabeckham'),
                        (	125,	1,	'instagram',	'leratv'),
                        (	126,	1,	'instagram',	'p'),
                        (	127,	1,	'instagram',	'bellahadid'),
                        (	128,	1,	'instagram',	'gigihadid'),
                        (	129,	1,	'instagram',	'irinashayk'),
                        (	130,	1,	'instagram',	'dolinalina'),
                        (	131,	1,	'instagram',	'nadiamixalkova'),
                        (	132,	1,	'instagram',	'klyukina_d'),
                        (	133,	1,	'instagram',	'baranovskaya_tv'),
                        (	134,	1,	'instagram',	'uliaveronika'),
                        (	135,	1,	'instagram',	'missalena.92'),
                        (	136,	1,	'instagram',	'bilanofficial'),
                        (	137,	1,	'instagram',	'aleksa___official'),
                        (	138,	1,	'instagram',	'juliavmenshova'),
                        (	139,	1,	'instagram',	'goshakutsenko'),
                        (	140,	1,	'instagram',	'lenaperminova'),
                        (	141,	1,	'instagram',	'andrei_konchalovsky'),
                        (	142,	1,	'instagram',	'asmuskristina'),
                        (	143,	1,	'instagram',	'liza_arzamasova'),
                        (	144,	1,	'instagram',	'rosiehw'),
                        (	145,	1,	'instagram',	'tsiskaridzenikolay'),
                        (	146,	1,	'instagram',	'themarcjacobs'),
                        (	147,	1,	'instagram',	'kimkardashian'),
                        (	148,	1,	'instagram',	'maria_ivakova'),
                        (	149,	1,	'instagram',	'annatikhomirova_official'),
                        (	150,	1,	'instagram',	'm1r0slava_karpovich');");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
