{{- if .Values.googleTranslateKey.externalSecret -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "parser.fullname" . }}-google-translate-key
  labels:
    {{- include "parser.labels" . | nindent 4 }}
{{- if .Values.googleTranslateKey.externalSecret }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.googleTranslateKey.secretStoreName }}
  target:
    creationPolicy: Owner
  dataFrom: # fetch all properties from a specific Provider data
    - key: {{ .Values.googleTranslateKey.key }}
      {{- if .Values.googleTranslateKey.version }}
      version: "{{ .Values.googleTranslateKey.version }}"
      {{- end }}
{{- else }}
data:
  google-translate-credentials.json: {{ .Values.googleTranslateKey.value | b64enc }}
{{- end }}
