{{- if .Values.secrets.externalSecret -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "parser.fullname" . }}-secret
  labels:
    {{- include "parser.labels" . | nindent 4 }}
{{- if .Values.secrets.externalSecret }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.secretStoreName }}
  target:
    creationPolicy: Owner
  dataFrom: # fetch all properties from a specific Provider data
    - key: {{ .Values.secrets.key }}
      {{- if .Values.secrets.version }}
      version: "{{ .Values.secrets.version }}"
      {{- end }}
{{- else }}
data:
  DB_PASSWORD: {{ .Values.secrets.RAPIDAPI_TOKEN | b64enc }}
{{- end }}
