{{- if .Values.secrets.externalSecret -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "parser.fullname" . }}-secret
  labels:
    {{- include "parser.labels" . | nindent 4 }}
{{- if .Values.secrets.externalSecret }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcpProjectId }}
  data:
    - name: RAPIDAPI_TOKEN
      key: {{ .Values.secrets.key }}
      version: {{ .Values.secrets.version }}
      property: RAPIDAPI_TOKEN
{{- else }}
data:
  DB_PASSWORD: {{ .Values.secrets.RAPIDAPI_TOKEN | b64enc }}
{{- end }}
