{{- if .Values.googleTranslateKey.externalSecret -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "parser.fullname" . }}-google-translate-key
  labels:
    {{- include "parser.labels" . | nindent 4 }}
{{- if .Values.googleTranslateKey.externalSecret }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcpProjectId }}
  data:
    - name: google-translate-credentials.json
      key: {{ .Values.googleTranslateKey.key }}
      version: {{ .Values.googleTranslateKey.version }}
{{- else }}
data:
  google-translate-credentials.json: {{ .Values.googleTranslateKey.value | b64enc }}
{{- end }}
