{{- if .Values.googleTranslateKey.externalSecret -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "parser.fullname" . }}-google-translate-key
  labels:
    {{- include "parser.labels" . | nindent 4 }}
{{- if .Values.googleTranslateKey.externalSecret }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    creationPolicy: Owner
  data:
    - secretKey: google-translate-credentials.json
      remoteRef:
        key: "{{ .Values.googleTranslateKey.key }}"
        version: "{{ .Values.googleTranslateKey.version }}"
{{- else }}
data:
  google-translate-credentials.json: {{ .Values.googleTranslateKey.value | b64enc }}
{{- end }}
